Repository MyJetWallet/Flutter.JetWallet, pull requests merged in 2022-05, with the labels that each got.

#633 SPUI-1464/SPUI-1451 > Fix referral page UI
  lib/auth/screens/register/components/referral_code/components/show_referral_code_link.dart
Labels: conflict

#626 SPUI-1178/1198/1460/1226/1223/1496 > Payment methods (Circle)
  lib/app/screens/account/account.dart
  lib/app/shared/features/add_circle_card/helper/masked_text_input_formatter.dart
  lib/app/shared/features/add_circle_card/notifier/add_circle_card_notifier.dart
  lib/app/shared/features/add_circle_card/notifier/add_circle_card_notipod.dart
  lib/app/shared/features/add_circle_card/notifier/add_circle_card_state.dart
  lib/app/shared/features/add_circle_card/view/add_circle_card.dart
  lib/app/shared/features/add_circle_card/view/circle_billing_address/circle_billing_address.dart
  lib/app/shared/features/add_circle_card/view/circle_billing_address/components/country_selector_button.dart
  lib/app/shared/features/add_circle_card/view/circle_billing_address/components/show_country_selector.dart
  lib/app/shared/features/add_circle_card/view/components/circle_progress_indicator.dart
  lib/app/shared/features/add_circle_card/view/components/continue_button_frame.dart
  lib/app/shared/features/add_circle_card/view/components/scrolling_frame.dart
  lib/app/shared/features/enter_card_details/notifier/enter_card_details_notifier.dart
  lib/app/shared/features/enter_card_details/notifier/enter_card_details_notipod.dart
  lib/app/shared/features/enter_card_details/notifier/enter_card_details_state.dart
  lib/app/shared/features/enter_card_details/view/enter_card_details.dart
  lib/app/shared/features/payment_methods/notifier/payment_methods_notifier.dart
  lib/app/shared/features/payment_methods/view/components/add_button.dart
  lib/app/shared/features/payment_methods/view/payment_methods.dart
  lib/app/shared/helpers/is_card_expired.dart
  lib/app/shared/helpers/last_n_chars.dart
  lib/core/app/app.dart
  lib/router/notifier/update_notifier/update_notifier.dart
  lib/service/services/circle/model/add_card/add_card_request_model.dart
  lib/service/services/circle/model/circle_card.dart
  plugins/simple_kit/assets/images/ellipsis.png
  plugins/simple_kit/lib/src/buttons/basic_buttons/base/simple_base_button.dart
  plugins/simple_kit/lib/src/buttons/basic_buttons/secondary_button/base/simple_base_secondary_button.dart
  plugins/simple_kit/lib/src/buttons/basic_buttons/secondary_button/dark/simple_dark_secondary_button_1.dart
  plugins/simple_kit/lib/src/buttons/basic_buttons/secondary_button/dark/simple_dark_secondary_button_2.dart
  plugins/simple_kit/lib/src/buttons/basic_buttons/secondary_button/light/simple_light_secondary_button_1.dart
  plugins/simple_kit/lib/src/buttons/basic_buttons/secondary_button/light/simple_light_secondary_button_2.dart
  plugins/simple_kit/lib/src/buttons/basic_buttons/secondary_button/public/simple_secondary_button_1.dart
  plugins/simple_kit/lib/src/buttons/basic_buttons/secondary_button/public/simple_secondary_button_2.dart
  plugins/simple_kit/lib/src/buttons/basic_buttons/text_button/base/simple_base_text_button.dart
  plugins/simple_kit/lib/src/fields/standard_field/base/simple_base_standard_field.dart
  plugins/simple_kit/lib/src/fields/standard_field/light/simple_light_standard_field.dart
  plugins/simple_kit/lib/src/fields/standard_field/public/simple_standard_field.dart
  plugins/simple_kit/lib/src/icons/24x24/public/action_buy/simple_action_buy_icon.dart
  plugins/simple_kit/lib/src/shared/components/simple_field_divider_frame.dart
  plugins/simple_kit/lib/src/shared/components/simple_show_alert_popup.dart
  plugins/simple_kit/lib/src/shared/components/stack_loader/notifier/stack_loader_notifier.dart
  pubspec.yaml
Labels: approved, waiting for QA testing

#644 SPUI-1443/1418 > Fix SignUp screen layout
  lib/auth/screens/register/components/mailing_checkbox/mailing_checkbox.dart
  lib/auth/screens/register/components/referral_code/components/no_referral_code.dart
  lib/auth/screens/register/register.dart
  plugins/simple_kit/lib/src/agreements/simple_privacy_policy/components/simple_policy_rich_text.dart
  plugins/simple_kit/lib/src/agreements/simple_privacy_policy/simple_policy_checkbox.dart
  plugins/simple_kit/lib/src/shared/components/simple_spacers.dart
Labels: approved

#645 SPUI-1342 > Fix transaction list error state
  lib/app/shared/features/actions/action_recurring_info/action_recurring_info.dart
  lib/app/shared/features/transaction_history/view/transaction_hisotry.dart
  lib/app/shared/features/wallet/view/components/wallet_body/components/transactions_list/transactions_list.dart
  lib/app/shared/features/wallet/view/components/wallet_body/wallet_body.dart
Labels: approved

#646 SPUI-1441 > Fix Help Center icon + header
  lib/app/screens/account/account.dart
  lib/app/screens/account/components/help_center_web_view.dart
  plugins/simple_kit/assets/icons/light/24x24/profile/question/question.svg
  plugins/simple_kit/lib/simple_kit.dart
  plugins/simple_kit/lib/src/icons/24x24/light/question/simple_light_question_icon.dart
  plugins/simple_kit/lib/src/icons/24x24/public/question/simple_question_icon.dart
  plugins/simple_kit/pubspec.yaml
Labels: requested changes

#638 SPUI-1453 > Disclaimer
  assets/images/disclaimer.png
  lib/app/shared/features/disclaimer/helpers/disclaimer_questions_parser.dart
  lib/app/shared/features/disclaimer/model/disclaimer_model.dart
  lib/app/shared/features/disclaimer/notifier/disclaimer_notifier.dart
  lib/app/shared/features/disclaimer/notifier/disclaimer_notipod.dart
  lib/app/shared/features/disclaimer/notifier/disclaimer_state.dart
  lib/app/shared/features/disclaimer/view/components/disclaimer_checkbox.dart
  lib/app/shared/features/disclaimer/view/components/disclaimer_popup.dart
  lib/app/shared/features/disclaimer/view/disclaimer.dart
  lib/router/notifier/startup_notifier/startup_notifier.dart
  lib/router/view/router.dart
  lib/service/services/disclaimer/model/disclaimers_request_model.dart
  lib/service/services/disclaimer/model/disclaimers_response_model.dart
  lib/service/services/disclaimer/service/disclaimers_service.dart
  lib/service/services/disclaimer/service/services/get_disclaimer_service.dart
  lib/service/services/disclaimer/service/services/save_disclaimer_service.dart
  lib/service/services/info/model/session_info_response_model.dart
  lib/service/services/signal_r/model/recurring_buys_model.dart
  lib/shared/constants.dart
  lib/shared/notifiers/user_info_notifier/user_info_notifier.dart
  lib/shared/notifiers/user_info_notifier/user_info_state.dart
  lib/shared/providers/service_providers.dart
Labels: approved

#649 SPUI-1452 > Display remaining time for unblock on sign in
  lib/auth/screens/login/login.dart
  lib/service/shared/helpers/handle_api_responses.dart
Labels: waiting for QA testing

#650 SPUI-1534, SPUI-1537 > Fix recurring buy
  lib/app/shared/features/actions/action_recurring_manage/action_recurring_manage.dart
  lib/app/shared/features/actions/action_recurring_manage/components/action_recurring_manage_item.dart
  lib/app/shared/features/wallet/view/components/wallet_body/components/transactions_list_item/components/transaction_details/components/common_transaction_details_block.dart
  lib/app/shared/features/wallet/view/components/wallet_body/components/transactions_list_item/components/transaction_details/recurring_buy_details.dart
  lib/app/shared/features/wallet/view/components/wallet_body/wallet_body.dart
Labels: requested changes

#686 SPUI-1603 > Hide "setup recurring buy" button in specific cases
  lib/app/shared/features/market_details/view/market_details.dart
  lib/app/shared/features/wallet/view/components/wallet_body/wallet_body.dart
  lib/app/shared/helpers/supports_recurring_buy.dart
Labels: high priority

#685 SPUI-1601 > Hide recurring selector on buy when simplex is active
  codemagic.yaml
  lib/app/shared/features/currency_buy/notifier/currency_buy_notifier/currency_buy_notifier.dart
  lib/app/shared/features/currency_buy/view/components/recurring_selector.dart
  lib/app/shared/features/currency_buy/view/curency_buy.dart
Labels: high priority

#668 SPUI-1520 > Phone confirmation flow change
  lib/app/shared/features/profile_details/view/profile_details.dart
  plugins/simple_kit/assets/images/phone_change.png
  plugins/simple_kit/lib/src/shared/constants.dart
Labels: requested changes

#694 SPUI-1316 > Login flow update
  lib/auth/screens/login/login.dart
  lib/auth/shared/notifiers/authentication_notifier/authentication_notifier.dart
  lib/service/services/authentication/service/services/login_service.dart
  lib/service/shared/helpers/handle_api_responses.dart
  lib/shared/helpers/timespan_to_duration.dart
Labels: merged with localization
