Repository MyJetWallet/Flutter.JetWallet, pull requests merged in 2022-03, with the labels that each got.

#501 Update tag versioning in CI/CD
  codemagic.yaml
  pubspec.yaml
Labels: 1.2.1

#498 SPUI-1218 > Fix copied in transaction history
  lib/app/shared/features/wallet/helper/is_operation_support_copy.dart
  lib/app/shared/features/wallet/helper/show_transaction_details.dart
  lib/app/shared/features/wallet/view/components/transaction_item.dart
  lib/app/shared/features/wallet/view/components/wallet_body/components/transactions_list_item/components/transaction_details/components/common_transaction_details_block.dart
Labels: 1.2.1

#494 SPUI-1031 > Permission camera
  lib/app/shared/features/kyc/view/components/choose_documents/choose_documents.dart
Labels: 1.3.0

#493 SPUI-1265 > Add description for error codes
  lib/app/shared/features/crypto_deposit/notifier/crypto_deposit_notifier.dart
  lib/service/shared/helpers/error_codes_description.dart
  lib/service/shared/helpers/handle_api_responses.dart
Labels: 1.3.0

#497 SPUI-1263 > Deposit UI fixes
  lib/app/shared/features/crypto_deposit/view/components/crypto_deposit_with_address.dart
  lib/app/shared/features/crypto_deposit/view/components/crypto_deposit_with_address_and_tag/crypto_deposit_with_address_and_tag.dart
  lib/app/shared/features/crypto_deposit/view/crypto_deposit.dart
  plugins/simple_kit/lib/src/notifications/view/simple_notification_box.dart
  plugins/simple_kit/lib/src/shared/components/qr_code_fields/simple_address_field_with_copy.dart
Labels: 1.3.0, reviewed

#485 SPUI-1203 > Add conversion to base currency
  lib/app/shared/features/wallet/view/components/wallet_body/components/transactions_list_item/components/transaction_details/components/common_transaction_details_block.dart
  lib/service/services/operation_history/model/operation_history_response_model.dart
Labels: 1.3.0

#506 SPUI-1306 > Add precache of onboarding images
  lib/auth/screens/onboarding/onboarding_screen.dart
  lib/auth/screens/splash/splash_screen.dart
Labels: 1.3.0

#495 SPUI-1261 > Change allow camera ui
  assets/images/allow_camera.png
  lib/app/shared/features/kyc/view/components/allow_camera/allow_camera.dart
Labels: 1.3.0, reviewed

#515 Add components for actions small screens
  lib/app/shared/features/convert/view/convert.dart
  lib/app/shared/features/currency_buy/view/curency_buy.dart
  lib/app/shared/features/currency_sell/view/currency_sell.dart
  lib/app/shared/features/currency_withdraw/view/screens/withdrawal_amount.dart
  lib/app/shared/features/send_by_phone/view/screens/send_by_phone_amount.dart
  plugins/simple_kit/lib/example/actions/examples/simple_action_price_field_example.dart
  plugins/simple_kit/lib/example/actions/examples/simple_payment_select_asset_example.dart
  plugins/simple_kit/lib/example/actions/examples/simple_payment_select_contact_example.dart
  plugins/simple_kit/lib/example/actions/examples/simple_payment_select_contact_without_name_example.dart
  plugins/simple_kit/lib/example/actions/examples/simple_payment_select_default_example.dart
  plugins/simple_kit/lib/example/actions/examples/simple_payment_select_fiat_example.dart
  plugins/simple_kit/lib/example/keyboards/examples/simple_numeric_keyboard_amount/simple_numeric_keyboard_amount_example.dart
  plugins/simple_kit/lib/example/keyboards/examples/simple_numeric_keyboard_amount/simple_numeric_keyboard_amount_guides.dart
  plugins/simple_kit/lib/simple_kit.dart
  plugins/simple_kit/lib/src/actions/simple_action_price_field.dart
  plugins/simple_kit/lib/src/actions/simple_payment_select_asset.dart
  plugins/simple_kit/lib/src/actions/simple_payment_select_contact.dart
  plugins/simple_kit/lib/src/actions/simple_payment_select_contact_without_name.dart
  plugins/simple_kit/lib/src/actions/simple_payment_select_default.dart
  plugins/simple_kit/lib/src/actions/simple_payment_select_fiat.dart
  plugins/simple_kit/lib/src/bottom_sheets/components/basic_bottom_sheet/components/basic_bottom_sheet.dart
  plugins/simple_kit/lib/src/keyboards/components/numeric_keyboard_frame.dart
  plugins/simple_kit/lib/src/keyboards/simple_numeric_keyboard_amount.dart
  plugins/simple_kit/lib/src/keyboards/simple_numeric_keyboard_pin.dart
  plugins/simple_kit/lib/src/shared/components/simple_get_widget_size.dart
  plugins/simple_kit/lib/src/shared/models/simple_widget_size.dart
Labels: 1.3.0

#496 SPUI-987 > Add dynamic gift bonus
  ios/Runner.xcodeproj/xcshareddata/xcschemes/dev.xcscheme
  ios/Runner.xcodeproj/xcshareddata/xcschemes/prod.xcscheme
  ios/Runner.xcodeproj/xcshareddata/xcschemes/stage.xcscheme
  lib/app/screens/account/account.dart
  lib/app/screens/portfolio/view/components/portfolio_header.dart
Labels: 1.3.0, reviewed

#500 SPUI-1033 > Add search to actions
  lib/app/shared/features/actions/action_buy/action_buy.dart
  lib/app/shared/features/actions/action_deposit/action_deposit.dart
  lib/app/shared/features/actions/action_receive/action_receive.dart
  lib/app/shared/features/actions/action_sell/action_sell.dart
  lib/app/shared/features/actions/action_send/action_send.dart
  lib/app/shared/features/actions/action_withdraw/action_withdraw.dart
  lib/app/shared/features/actions/shared/components/action_bottom_sheet_header.dart
  lib/app/shared/features/actions/shared/notifier/action_search_notifier.dart
  lib/app/shared/features/actions/shared/notifier/action_search_notipod.dart
  lib/app/shared/features/actions/shared/notifier/action_search_state.dart
Labels: 1.3.0, reviewed

#510 SPUI-1274 > Add fee in transaction
  lib/app/shared/features/convert/notifier/preview_buy_with_asset_notifier/preview_convert_notifier.dart
  lib/app/shared/features/convert/notifier/preview_buy_with_asset_notifier/preview_convert_state.dart
  lib/app/shared/features/convert/view/preview_convert.dart
  lib/app/shared/features/wallet/view/components/wallet_body/components/transactions_list_item/components/transaction_details/buy_sell_details.dart
  lib/service/services/operation_history/model/operation_history_response_model.dart
  lib/service/services/swap/model/get_quote/get_quote_response_model.dart
Labels: reviewed, 1.2.2

#504 SPUI-1279 > Sort asset by weight in convert
  lib/app/shared/features/convert/view/components/convert_row/convert_row.dart
  lib/app/shared/features/convert/view/convert.dart
  lib/app/shared/helpers/currencies_helpers.dart
  lib/app/shared/models/currency_model.dart
Labels: reviewed, 1.2.2

#523 SPUI-1286 > Small success failure screen
  lib/app/shared/features/currency_buy/view/preview_buy_with_asset.dart
  lib/app/shared/features/currency_withdraw/view/screens/withdrawal_preview.dart
  lib/app/shared/features/kyc/view/components/kyc_selfie/components/success_kys_screen.dart
  lib/app/shared/features/send_by_phone/view/screens/send_by_phone_preview.dart
  lib/shared/components/result_screens/failure_screen/components/failure_animation.dart
  lib/shared/components/result_screens/failure_screen/failure_screen.dart
  lib/shared/components/result_screens/success_screen/components/success_animation.dart
  lib/shared/components/result_screens/success_screen/success_screen.dart
Labels: 1.2.2

#524 SPUI-991 > Small send by phone
  lib/app/shared/features/send_by_phone/view/screens/send_by_phone_amount.dart
Labels: 1.2.2

#526 SPUI-914 > Small sell screen
  lib/app/shared/features/currency_sell/view/currency_sell.dart
Labels: 1.2.2

#528 SPUI-1019 > Add small buy screen
  lib/app/shared/features/currency_buy/view/curency_buy.dart
Labels: 1.2.2

#527 SPUI-915 > Small convert screen
  lib/app/shared/features/convert/view/convert.dart
Labels: 1.3.0, reviewed

#516 SPUI-1021 > Create empty state for country search
  lib/app/shared/components/empty_search_result.dart
  lib/app/shared/features/kyc/view/components/choose_documents/components/show_kyc_country_picker.dart
Labels: 1.3.0, reviewed

#513 SPUI-776 > Market tabs border
  lib/app/shared/components/bottom_tabs/components/bottom_tab.dart
Labels: 1.3.0, reviewed

#521 SPUI-1005 > Tap states for some elements
  plugins/simple_kit/lib/src/buttons/basic_buttons/text_button/base/simple_base_text_button.dart
  plugins/simple_kit/lib/src/buttons/basic_buttons/text_button/dark/simple_dark_text_button_1.dart
  plugins/simple_kit/lib/src/buttons/basic_buttons/text_button/dark/simple_dark_text_button_2.dart
  plugins/simple_kit/lib/src/buttons/basic_buttons/text_button/light/simple_light_text_button_1.dart
  plugins/simple_kit/lib/src/buttons/basic_buttons/text_button/light/simple_light_text_button_2.dart
  plugins/simple_kit/lib/src/keyboards/components/keys/keyboard_key.dart
Labels: 1.3.0, reviewed

#514 SPUI-719 > News
  lib/app/screens/navigation/view/components/screens.dart
  lib/app/screens/news/news.dart
  lib/app/screens/news/notifier/news_notifier.dart
  lib/app/screens/news/notifier/news_notipod.dart
  lib/app/screens/news/notifier/news_state.dart
  lib/app/screens/news/notifier/news_union.dart
  lib/app/screens/news/view/components/news_list.dart
  lib/app/screens/news/view/components/news_loading_skeleton/components/news_loading_item.dart
  lib/app/screens/news/view/components/news_loading_skeleton/news_loading_skeleton.dart
  lib/app/screens/news/view/news.dart
  lib/app/shared/features/market_details/view/components/market_news_block/market_news_block.dart
  lib/app/shared/features/news/notifier/education_news_notifier.dart
  lib/app/shared/features/news/notifier/education_news_notipod.dart
  lib/app/shared/features/news/notifier/education_news_state.dart
  lib/app/shared/features/news/provider/education_news_fpod.dart
  lib/service/services/news/model/news_request_model.dart
  lib/service/services/news/services/news_service.dart
  plugins/simple_kit/lib/src/news/simple_news_category.dart
Labels: 1.3.0, reviewed

#522 SPUI-990 > Small withdrawal screen
  lib/app/shared/features/currency_withdraw/view/currency_withdraw.dart
  lib/app/shared/features/currency_withdraw/view/screens/withdrawal_amount.dart
Labels: 1.3.0, blocked
