Repository MyJetWallet/Flutter.JetWallet, pull requests merged in 2022-04, with the labels that each got.

#529 SPUI-1053 > Multiple taping on share button (referral, deposit addres…
  lib/app/shared/features/crypto_deposit/view/crypto_deposit.dart
  lib/app/shared/features/send_by_phone/view/screens/send_by_phone_notify_recipient.dart
  plugins/simple_kit/lib/src/referral_invite/simple_referral_invite_bottom_pinned.dart
Labels: reviewed, 1.4.0, needs second review

#532 SPUI-1302 > Add denied qr camera handler
  lib/app/shared/features/currency_withdraw/notifier/withdrawal_address_notifier/withdrawal_address_notifier.dart
  lib/app/shared/features/kyc/notifier/camera_permission/camera_permission_notifier.dart
  lib/app/shared/features/kyc/view/components/allow_camera/allow_camera.dart
  lib/app/shared/features/kyc/view/components/choose_documents/choose_documents.dart
Labels: reviewed, 1.4.0

#567 SPUI-1327 > Display earn banner and set colors for them
  lib/app/shared/features/rewards/notifier/reward/rewards_notipod.dart
  lib/app/shared/features/rewards/view/rewards.dart
  lib/app/shared/helpers/set_banner_color.dart
Labels: 1.4.0

#557 SPUI-1324 > Add color for day percentage in the quote
  lib/app/screens/market/helper/format_day_percentage_change.dart
  lib/app/shared/features/wallet/helper/show_interest_rate.dart
  lib/app/shared/features/wallet/view/components/wallet_body/components/card_block/components/wallet_card.dart
Labels: reviewed, 1.4.0

#533 SPUI-1277 > Add referral link to send
  lib/app/shared/features/send_by_phone/view/screens/send_by_phone_notify_recipient.dart
Labels: reviewed, 1.4.0

#562 SPUI 1322/1349/1350 > Header WebView simplex
  lib/app/screens/account/account.dart
  lib/app/screens/account/components/faq_web_view.dart
  lib/app/screens/news/view/components/news_list/components/news_web_view.dart
  lib/app/screens/news/view/components/news_list/news_list.dart
  lib/app/screens/news/view/news.dart
  lib/app/shared/features/currency_buy/view/simplex_web_view.dart
  plugins/simple_kit/lib/src/headers/simple_small_header.dart
Labels: reviewed, 1.4.0

#563 SPUI-1325 > Hide bottom sheet after convert success
  lib/app/screens/navigation/view/components/bottom_navigation_menu.dart
  lib/app/shared/features/convert/notifier/preview_buy_with_asset_notifier/preview_convert_notifier.dart
Labels: reviewed, 1.4.0

#564 SPUI-1027 > Add left padding for icon in SStandardField
  plugins/simple_kit/lib/src/fields/standard_field/light/simple_light_standard_field.dart
Labels: reviewed, 1.4.0

#566 SPUI-1036 > Add market banners indicator
  lib/app/screens/account/components/account_banner_list.dart
  lib/app/screens/market/view/components/market_banners/market_banners.dart
Labels: 1.4.0

#568 SPUI-1303 > Make timer working in background
  lib/app/shared/features/phone_verification/view/phone_verification.dart
  lib/main_development.dart
  lib/shared/features/two_fa_phone/view/two_fa_phone.dart
  lib/shared/notifiers/timer_notifier/timer_notifier.dart
  plugins/simple_kit/lib/src/buttons/resend_button/simple_resend_button.dart
Labels: 1.4.0

#569 SPUI-1182 > Fix pinned scroll
  lib/app/screens/portfolio/view/components/empty_portfolio/components/earn_bottom_sheet/earn_bottom_sheet.dart
Labels: 1.4.0

#570 SPUI-1328 > Fix text on invite friend page
  lib/shared/services/deep_link_service.dart
  plugins/simple_kit/lib/src/referral_invite/simple_referral_invite_body.dart
Labels: 1.4.0

#571 SPUI-1305 > Сhange edit code flow
  lib/app/shared/features/currency_withdraw/view/screens/withdrawal_confirm.dart
  lib/app/shared/features/phone_verification/view/phone_verification.dart
  lib/app/shared/features/send_by_phone/view/screens/send_by_phone_confirm.dart
  lib/auth/screens/email_verification/view/email_verification.dart
  lib/auth/screens/forgot_password/view/confirm_password_reset.dart
  lib/shared/components/pin_code_field.dart
  lib/shared/features/two_fa_phone/view/two_fa_phone.dart
Labels: 1.4.0

#572 SPUI-1340 > Update remote config fetching interval
  lib/shared/services/remote_config_service/service/remote_config_service.dart
Labels: 1.4.0

#591 SPUI-1309 > Display simplex on small screen
  plugins/simple_kit/lib/src/asset_items/simple_action_item.dart
Labels: 1.4.0

#597 SPUI-1048 > Reset password multipage fix
  lib/auth/screens/reset_password/view/reset_password.dart
Labels: 1.4.0

#577 SPUI-1329/1358/1359/1357/1354/1345 > New flow buy deposit
  lib/app/screens/market/provider/market_items_pod.dart
  lib/app/screens/navigation/view/components/bottom_navigation_menu.dart
  lib/app/shared/components/show_start_earn_options.dart
  lib/app/shared/features/actions/action_buy/action_buy.dart
  lib/app/shared/features/actions/action_receive/action_receive.dart
  lib/app/shared/features/actions/action_send/action_send.dart
  lib/app/shared/features/actions/shared/notifier/action_search_notifier.dart
  lib/app/shared/features/actions/shared/notifier/action_search_state.dart
  lib/app/shared/features/currency_buy/notifier/currency_buy_notifier/currency_buy_notifier.dart
  lib/app/shared/features/currency_buy/notifier/preview_buy_with_asset_notifier/preview_buy_with_asset_notifier.dart
  lib/app/shared/features/currency_buy/view/curency_buy.dart
  lib/app/shared/features/market_details/view/components/balance_block/components/balance_action_buttons.dart
  lib/app/shared/features/wallet/view/components/action_button/action_button.dart
  lib/app/shared/helpers/icon_url_from.dart
  lib/app/shared/models/currency_model.dart
  lib/app/shared/providers/currencies_pod/currencies_pod.dart
  plugins/simple_kit/lib/example/action_sheet/examples/simple_menu_action_sheet_example.dart
  plugins/simple_kit/lib/simple_kit.dart
  plugins/simple_kit/lib/src/actions/simple_payment_select_empty_balance.dart
  plugins/simple_kit/lib/src/asset_items/simple_action_item.dart
  plugins/simple_kit/lib/src/bottom_sheets/sheets/show_menu_action_sheet.dart
Labels: requested changes, 1.4.0

#589 SPUI-1373/1372 > Add history simplex
  lib/app/shared/features/wallet/helper/operation_name.dart
  lib/app/shared/features/wallet/notifier/operation_history_notifier.dart
  lib/app/shared/features/wallet/view/components/transaction_item.dart
  lib/app/shared/features/wallet/view/components/wallet_body/components/transactions_list_item/components/transaction_details/buy_simplex_details.dart
  lib/app/shared/features/wallet/view/components/wallet_body/components/transactions_list_item/components/transaction_details/components/common_transaction_details_block.dart
  lib/app/shared/features/wallet/view/components/wallet_body/components/transactions_list_item/transaction_list_item.dart
  lib/service/services/operation_history/model/operation_history_response_model.dart
Labels: reviewed, requested changes, 1.4.0

#600 SPUI-1389/1390/1391 > Referral code
  lib/app/shared/features/actions/shared/components/action_bottom_sheet_header.dart
  lib/auth/screens/register/components/mailing_checkbox/mailing_checkbox.dart
  lib/auth/screens/register/components/referral_code/components/invalid_referral_code.dart
  lib/auth/screens/register/components/referral_code/components/loading_referral_code.dart
  lib/auth/screens/register/components/referral_code/components/no_referral_code.dart
  lib/auth/screens/register/components/referral_code/components/show_referral_code_link.dart
  lib/auth/screens/register/components/referral_code/components/valid_referral_code.dart
  lib/auth/screens/register/components/referral_code/referral_code.dart
  lib/auth/screens/register/notifier/referral_code_link_notifier.dart
  lib/auth/screens/register/notifier/referral_code_link_notipod.dart
  lib/auth/screens/register/notifier/referral_code_link_state.dart
  lib/auth/screens/register/notifier/referral_code_link_union.dart
  lib/auth/screens/register/register.dart
  lib/service/services/referral_code_service/model/validate_referral_code_request_model.dart
  lib/service/services/referral_code_service/model/validate_referral_code_response_model.dart
  lib/service/services/referral_code_service/service/referral_code_service.dart
  lib/service/services/referral_code_service/service/services/validate_referral_code_service.dart
  lib/shared/providers/service_providers.dart
  lib/shared/services/local_storage_service.dart
  plugins/simple_kit/lib/src/agreements/simple_privacy_policy/simple_policy_checkbox.dart
  plugins/simple_kit/lib/src/colors/view/simple_colors.dart
  plugins/simple_kit/lib/src/colors/view/simple_colors_dark.dart
  plugins/simple_kit/lib/src/colors/view/simple_colors_light.dart
Labels: requested changes, 1.4.0

#606 SPUI-1431 > Fix reward ui
  lib/app/shared/features/rewards/helper/reward_description_item.dart
  lib/app/shared/features/rewards/helper/set_reward_description_item.dart
  lib/app/shared/features/rewards/helper/set_reward_indicator_complete.dart
  lib/app/shared/features/rewards/view/rewards.dart
  plugins/simple_kit/lib/src/banners/rewards_banner/simple_three_steps_reward_banner.dart
Labels: reviewed, conflict

#593 SPUI-1323 > Simplex in progress transaction info
  lib/app/screens/portfolio/view/components/portfolio_with_balance/components/portfolio_with_balance_body.dart
  lib/app/shared/features/wallet/helper/navigate_to_wallet.dart
  lib/app/shared/features/wallet/view/components/wallet_body/components/card_block/components/wallet_card.dart
  lib/app/shared/features/wallet/view/components/wallet_body/components/card_block/components/wallet_card_collapsed.dart
  lib/app/shared/features/wallet/view/components/wallet_body/components/transactions_list_item/components/transaction_list_item_header_text.dart
  lib/app/shared/features/wallet/view/components/wallet_body/components/transactions_list_item/transaction_list_item.dart
  plugins/simple_kit/lib/src/asset_items/simple_wallet_item.dart
Labels: reviewed, requested changes
